version: 2

references:
  circleci_docker_primary: &circleci_docker_primary trussworks/circleci-docker-primary:tf12-0f54e1d0b033fd7639ae287ecd4445b4aa9bd37a

jobs:
  validate:
    docker:
      - image: *circleci_docker_primary
    steps:
      - checkout
      - restore_cache:
          keys:
            - pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
      - run:
          name: Run pre-commit tests
          command: pre-commit run --all-files
      - save_cache:
          key: pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - ~/.cache

  terratest:
    docker:
      - image: *circleci_docker_primary
    steps:
      - checkout
      - run:
          name: Validate aws credentials
          command: aws s3 ls

workflows:
  version: 2
  validate:
    jobs:
      - validate
      - terratest
